### ISSUE TITLE
CMAF - require a strict mapping of file extension to MIME type

### ISSUE THREAD

**Issue by wilaw** [irajs/CMAF#2]
In Section 7.2 we have "_If ‘cmfc’ is the major_brand, file names SHOULD use the file extension “*.cmff”, and use the Internet Media Type (MIME type) registered for that extension._ "
Having a consistent file extensions is a great restriction as it will clearly identify a CMAF formatted segmented in a production workflow, which has many benefits from a debugging and asset management point of view. However, the current draft calls for the same file extension to be used with different MIME-types to describe the internal content as either video, audio or text. This is not practical in the real world of CDN delivery, where MIME-type headers are often applied dynamically by edge servers. How would an edge server know which MIME-type to use as it delivers a .cmff file from origin storage, or working backwards up the delivery chain, how would a storage server know what MIME-type to attach to a binary asset that it is delivering? It would either need to store that info as metadata in some parallel data structure, or it would need to parse the codec in order to determine the type of content. Both are unwieldy solutions and will server to hinder the adoption of CMAF. A support person examining a set of files on disk (a.cmff, b.cmff, c.cmff for example) cannot tell whether they are referencing audio, video or text segments. 

I believe a more practical and robust solution is to mandate a set of file extensions that have a 1:1 correspondence with MIME-type. With this in place, any server can inspect the file extension and dynamically apply a MIME-type and any human viewing the segment can know the type of content it carries without having to observe HTTP headers. My proposal would be:

If “cmfc” is the major brand, then file names SHOULD use the file extension and MIME-type mappings defined below, depending on the encapsulated payload

.cmfv  (video/mp4) - also to be used for muxed content
.cmfa (audio/mp4)
.cmft (application/mp4)

I don't have religion about the actual file extensions to be used, or the associated MIME types. These can be debated. 

Thanks

Will

**Comment by ghost** [comment]
Good suggestion.  I think the extension would be determined by the Media Profile compatibility brand in each 'ftyp' that are listed in Annex A2, A3, or A4, or externally specified and registered as a brand at MP4RA.org.  
Those correspond to the IANA media type nodes, like /audio and /video. 

Subtitles are identified as /Text or /Application, with VTT the former and TTML the latter (since it is markup language, styles, and optionally images that requires interpretation and decoding).  We should also consider timed metadata tracks, which are specifically mentioned now in the contribution draft. 4 or 5 extensions and MIME types.  

Other formats that have done this specialized the "codecs" parameters for the media type, and added features, such as encryption scheme 4CC, to indicate if and how samples are encrypted.  The codecs parameters can be signaled in manifests and is more useful for canPlayType(MIME, codecs) queries.  The file extension only tells you the media type, but that may be sufficient for file management. Parsing the 'ftyp' box for the Media Profile brand tells you a lot about content/player compatibility.

**Comment by dwsinger** [comment]
done as suggested in M38228-v2 (May)
