### ISSUE TITLE
Table 5- Video Metadata Profiles

### ISSUE THREAD

**Issue by YasserSyed** [irajs/CMAF#4]
1) Table 5- Video Metadata Profiles- HEVC should always be declaring a tier with the profile and level. Table is not indicating that.
2) Table 5- Video Metadata Profile- do we need to indicate the container for the color gamuts (e.g. BT 2020 container for BT709 calue)
3) Table 5- Video Metadata Profile- lower resolutions in a profile can have a higher max framerate- e.g. HD@120 is supportable in level 5.1, UHD only goes up to 60 Hz. How do we indicate an HD @120Hz stream?

**Comment by dwsinger** [comment]
filed on w15947 (San Diego output)

**Comment by dwsinger** [comment]
Table 9 in A.2 in 38228

**Comment by ghost** [comment]
1. HEVC Main Tier will be added.
2. Default grading and color volume are specified, and it is stated that non-default values SHOULD be described by SEI NALs in the video sample entry.
3. V2 framerates were only limited by the codec level limits (column labelled Max Framerate at max frame size). 
   AHG teleconference in May decided to constrain the maximum framerate regardless of resolution, e.g. HD Media Profile limited to 60Hz for 720P and below.  HDHF Media Profile is also 60Hz, but allows 1080P60 because it is a higher level.  Higher framerates, like 120Hz, would need to be defined and registered in new Media Profiles and brands.
