### ISSUE TITLE
7.5.18 and 7.5.16 -- Handling 'blank time' and loss

### ISSUE THREAD

**Issue by dwsinger** [irajs/CMAF#47]
We need to address (a) known 'blank' time and (b) known ‘my dog ate this data', in a more coherent way.
Need to discuss the duration-is-empty flag (I think we don’t allow it, but see the track run box which talks of fragments with duration but no samples, and this is the only way to do that afaik).

We may need a 'null' codec; the presence of a 'null' sample entry in a track would be a signal that there may be blank time, and then (zero-size, but non-zero-duration) samples can be associated with that entry. We may need two, both 'null' (in the program material, there is nothing here) and 'lost' (there may have been data for this interval, but my dog ate it).

**Comment by dwsinger** [comment]
Current thinking is to define two new codec types, probably in the ISO BMFF:  'null', meaning that we know nothing happens during this time interval; and 'lost' meaning that someone knows that they don't know what was supposed to be in this time interval (and hence loss concealment might be considered, or an apology such as "We regret the loss of picture").  Comments welcome.

**Comment by dwsinger** [comment]
filed on m38228/v1

**Comment by ghost** [comment]
We have added recommendations within the scope of CMAF, such as extending the duration of video samples or repeating them to maintain the presentation timeline when samples are lost on input or encoding.  Audio may be more difficult because silence needs to be encoded, samples can't just be repeated.
Lost Segments, due to encoding or delivery problems, should be handled by the streaming protocol so they don't result in 404s or the media pipeline failing because it can't maintain A/V sync. If a manifest indicates a gap, a player could skip it (VOD) or pause and skip (live), or a new Presentation (e.g. Period) could be started with available content.  This is out of normative scope for CMAF, but mentioned in the Appendix on error handling.
A file system method of recording "null" samples needs to be specified in ISOBMFF, not CMAF.  The problem remains that describing missing samples doesn't solve the problem of most A/V pipelines failing when A/V sync is lost, especially when there are audio gaps.

I think CMAF now recommends what is in its scope, and ISOBMFF should consider file format solutions to gaps in samples and movie fragments.
