### ISSUE TITLE
2nd draft: 9.5.3 remove video track statement and make factual statement on padding.

### ISSUE THREAD

**Issue by irajs** [irajs/CMAF#64]
Comment 44: “Video Tracks SHALL only encode spatial samples intended for presentation on all displays. Padding such as letterbox and pillarbox bars SHOULD NOT be encoded.”

What does “spatial samples intended for presentation all displays” mean? Active video definition that we said we would write. 

ACTION: Remove first sentence “Video Tracks SHALL only encode …” and leave only Padding… Make it an only – replace with a FACTUAL statement.

**Comment by dwsinger** [comment]
filed on m38228/v2

**Comment by ghost** [comment]
Rewritten to describe the cropping and decoding operation, and the meaning of Height and Width parameters.  No behavior is stated for encoding only the active image, although we should say that somewhere, rather than rely on humans doing video encoding to deduce the system model from assumed Player decoding and framing behavior.
