### ISSUE TITLE
2nd draft: 9.5.4 Text should be agnostic to HDR formats

### ISSUE THREAD

**Issue by irajs** [irajs/CMAF#66]
Decision in San Diego was that the spec should be agnostic to HDR formats and defer detail to those profiles in annex. Here is the BBC proposal. 

“Video streams conforming to CMAF SHALL be encoded appropriately for the transfer characteristics and color parameters specified in each video Media Profile, and the Media Profile SHALL be indicated by that Media Profile’s compatibility brand in the CMAF Header. See Video Media Profiles and Track Brands Annex [A.2].

For all Media Profiles, unless signaled otherwise in Sequence Parameter Sets or SEI messages, video SHALL be assumed to be appropriate for presentation on a display which uses the electro-optic transfer function specified in [R1886] with a peak luminance of 100 cd/m2 in a reference viewing environment that complies with [R2035].

Video MAY be intended for presentation on a display which uses an electro-optic transfer function not specified in [R1886] with a peak luminance greater than 100 cd/m2, in which case, the transfer characteristics SHOULD be signaled by VUI and/or appropriate SEI messages, and also signaled in any associated manifest.”

ACTION: Replace language as given by BBC (Chris Poole)

**Comment by dwsinger** [comment]
filed on m38228/v2

**Comment by mikedo** [comment]
Although I agree that it should be HDR agnostic and defer the details to a media profile Annex, if all of the proposed text is destined for the "core provisions" of 9.5.4 and 9.4.2.4.2, then this is not flexible enough as there are other ways to signal HDR information than in SEI or VUI. So we still need to delete/move "in Sequence Parameter Sets or SEI messages".

**Comment by ghost** [comment]
The intent here is a requirement on Track specifications and Media Profiles to specify sufficient initialization information in the sample entry to configure color lookup, tone mapping, etc.; as well as transfer function, profile, level, width and height, etc., which are already required in VPS, SPS, PPS, NALs.

Since the necessary color calibration information is being carried in SEI NALs “whatever SEI NALs necessary for initialization” need to be defined by each Media Profile.  This should be clarified state a general requirement on the specification of Media Profiles.

The AVC and HEVC track bindings in CMAF, in combination with the Media Profiles, need to specify what parameter NALs and SEIs SHOULD or SHALL be in the DecoderConfigurationRecord for Media Profiles derived from those Track bindings.

We need to make it practical for devices playing a sequence of Presentations to rapidly initialize for continuous playback, and the Initialization Segment and sample entry are being defined by CMAF as the location of the initialization information.  Decoders aren’t expected to find initialization information in manifest, later in Media Segments, some unspecified out of band method, etc.  This has to work for streams, so a player can’t (or shouldn’t have to) scan ahead in a stream or file to find initialization information. Some standardization is needed for interoperability and performance. Just like the case of SPS and PPS NALs, it doesn’t’ preclude including additional NALs in Fragments used to decode and render the Fragment.

ISOBMFF video specs (Part 12 and 15) recommend that NALs necessary for decoder configuration be included in the AVCDecoderConfigurationRecord or HEVCDecoderConfigrationRecord, so the intent here is to make it a requirement that Media Profiles define what that means in terms of the range and gamut SEIs that should be included for initialization.

I think the requirement should be clarified, and specified by each Media Profile that doesn’t use the defaults, but not removed entirely.

Kilroy Hughes | Senior Digital Media Architect |Windows Azure Media Services | Microsoft Corporation
[cid:image001.png@01CDABBA.71FD8800]http://www.windowsazure.com/media

**Comment by mikedo** [comment]
Regarding: "The intent here is a requirement on Track specifications and Media Profiles to specify sufficient initialization information in the sample entry to configure..." - yes, we agree.  The problem is that the text proposed by BBC says explicitly, "VUI and SEI", thus prohibiting NAL or other signaling mechanisms.  The core constraints for all video needs to be less prescriptive than is being proposed. I suppose you could be exhaustive for all possible locations, but I believe it is adequate to state the requirement to provide it in the profile and stop there.

**Comment by mikedo** [comment]
(Editors, be careful not to undo m38555)

**Comment by ghost** [comment]
This section was modified to allow other means of configuration signaling defined by the video Media Profile.
