### ISSUE TITLE
2nd draft:  9.4.2.4.2 Visual Usability Information (VUI) Parameters

### ISSUE THREAD

**Issue by irajs** [irajs/CMAF#67]
Conformance testing will not work with ‘SHALL be assumed’. 

ACTION:  Replace “SHALL be assumed” with “is assumed”

**Comment by dwsinger** [comment]
filed on m38228/v2

**Comment by poolec** [comment]
The action here doesn't capture the whole of what was agreed at the 9th May call.
The initial discussion was of a BBC proposal to modify the wording of the sub-bullet "Video is graded in a viewing environment..." to something that more accurately describes the meaning.
We proposed that it read:
- Video is appropriate for presentation on a display which uses the electro-optic transfer function specified in [R1886] with a peak luminance of 100 cd/m2 in a reference viewing environment that complies with [R2035].

That new text was agreed (and then matches what was agreed for 9.5.4 in #66).

There was then a further point raised about the bullet that introduces this.  It was agreed that "SHALL be assumed" was wrong because this isn't a receiver spec and in any case, this text is re-stating something which is already specified elsewhere.  So it was agreed to change that to "is assumed".

So the complete action would be:
ACTION: In the bullet that begins "If colour_description_present_flag is set to 0", replace “SHALL be assumed” with “is assumed”.  Then in the sub-bullet that begins "Video is graded in a viewing environment", replace the whole text of the bullet with the following new wording: "Video is appropriate for presentation on a display which uses the electro-optic transfer function specified in [R1886] with a peak luminance of 100 cd/m2 in a reference viewing environment that complies with [R2035]."

**Comment by dwsinger** [comment]
done in the CD
