### ISSUE TITLE
What is the behavior if an emsg box is missed in a live stream?

### ISSUE THREAD

**Issue by YasserSyed** [irajs/CMAF#7]
What happens if an emsg box is missed in a live stream? Does a MPD play a role in informing the player?

**Comment by cconcolato** [comment]
My understanding is that nothing happens. You'll refresh the MPD at the time indicated in the MPD you didn't miss.

**Comment by dwsinger** [comment]
Unclear what change to the spec. is needed here; emsg handling is outside CMAF, CMAF merely needs to admit that they might exist.

**Comment by dwsinger** [comment]
filed on w15947 (San Diego output)

**Comment by ghost** [comment]
Resolved with regard to CMAF.  
Regarding DASH and MPD, an 'emsg' box can be repeated on multiple Segments for robustness, so that a player joining a live presentation can receive a repeated message if it missed the first instance.  This is the same behavior as SCTE-35 messages. Event messages are also represented in the MPD EventStream, so a player joining a live presentation or randomly accessing a PVR buffer can read the Event Messages on the timeline even when it doesn't read them on a Segment.
